networks: 
  dockercoins:
    internal: true
secrets:
  secret-hasher: 
    file: $PWD/hasher/hasher.rb
services:
  hasher:
    command:
      - 
        hasher.rb
    entrypoint:
      -
        ruby
    environment:
      autor: Fernando
    image: jfernandomg/ruby:sinatra-thin
    networks:
      -
        dockercoins
    restart: always
    secrets:
      -
        mode: 0400
        source: secret-hasher
        target: /data/hasher.rb
        uid: '65534'
    user: nobody
    working_dir: /data/
version: '3.9'
        
