apiVersion: v1
kind: Pod
metadata: 
 name: po-hasher
spec: 
 containers:
  -
   args:
    - 
     hasher.rb
   command:
    -
     ruby
   env:
    -
     name: autor
     value: fernando
   image: jfernandomg/ruby:sinatra-thin
   name: hasher
   ports:
    -
     containerPort: 80
     protocol: TCP
   volumeMounts:
    -
     mountPath: /data/hasher.rb
     name: volume-hasher
     readOnly: true 
     subPath: hasher.rb
status
