apiVersion: v1
kind: Pod
metadata: 
 name: po-hasher
spec: 
 containers:
  -
   args:
    - 
     hasher.rb
   command:
    -
     ruby
   env:
    -
     name: autor
     value: fernando
   image: jfernandomg/ruby:sinatra-thin
   name: hasher
   ports:
    -
     containerPort: 80
     protocol: TCP
    - 
     containerPort: 8080
     protocol: UDP
   volumeMounts:
    -
     mountPath: /data/hasher.rb
     name: volume-hasher
     readOnly: true 
     subPath: hasher.rb
   workingDir: /data/
 restartPolicy: Always
 volumes:
  -
   name: volume-hasher
   secret:
    defaultMode: 0400
    items:
     -
      key: hasher.rb
      mode: 0400
      path: hasher.rb
    secretName: secret-hasher
    
status
